'''
Authors: Joshua Moellers
The code for Running the balatro simulations and also for testing the simulations
'''

'''
class Config(object)
     |  Static methods defined here:
     |
     |  __new__(*args, **kwargs)
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |                                                                                                                                                                                                                                                                                                                 
     |  ante_end                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  available_max                                                                                                                                                                                                                                                                                                  
     |                                                                                                                                                                                                                                                                                                                 
     |  deck_max                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  discarded_max                                                                                                                                                                                                                                                                                                  
     |                                                                                                                                                                                                                                                                                                                 
     |  discards                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  joker_slots                                                                                                                                                                                                                                                                                                    
     |                                                                                                                                                                                                                                                                                                                 
     |  joker_slots_max                                                                                                                                                                                                                                                                                                
     |                                                                                                                                                                                                                                                                                                                 
     |  money_max                                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  plays                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  selected_max                                                                                                                                                                                                                                                                                                   
     |                                                                                                                                                                                                                                                                                                                 
     |  stage_max                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                       
    class GameEngine(object)                                                                                                                                                                                                                                                                                           
     |  GameEngine(config=None)                                                                                                                                                                                                                                                                                        
     |                                                                                                                                                                                                                                                                                                                 
     |  Methods defined here:                                                                                                                                                                                                                                                                                          
     |
     |  copy() -> added by Joshua Moellers
     |                                                                                                                                                                                                                                                                                                                 
     |  gen_action_space(self, /)                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  gen_actions(self, /)                                                                                                                                                                                                                                                                                           
     |                                                                                                                                                                                                                                                                                                                 
     |  handle_action(self, /, action)                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  handle_action_index(self, /, index)                                                                                                                                                                                                                                                                            
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Static methods defined here:                                                                                                                                                                                                                                                                                   
     |                                                                                                                                                                                                                                                                                                                 
     |  __new__(*args, **kwargs)                                                                                                                                                                                                                                                                                       
     |      Create and return a new object.  See help(type) for accurate signature.                                                                                                                                                                                                                                    
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Data descriptors defined here:                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  is_over                                                                                                                                                                                                                                                                                                        
     |                                                                                                                                                                                                                                                                                                                 
     |  is_win                                                                                                                                                                                                                                                                                                         
     |                                                                                                                                                                                                                                                                                                                 
     |  state                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                       
    class GameState(object)                                                                                                                                                                                                                                                                                            
     |  Methods defined here:                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  __repr__(self, /)                                                                                                                                                                                                                                                                                              
     |      Return repr(self).                                                                                                                                                                                                                                                                                         
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Static methods defined here:                                                                                                                                                                                                                                                                                   
     |                                                                                                                                                                                                                                                                                                                 
     |  __new__(*args, **kwargs)                                                                                                                                                                                                                                                                                       
     |      Create and return a new object.  See help(type) for accurate signature.                                                                                                                                                                                                                                    
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Data descriptors defined here:                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  action_history                                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  available                                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  deck                                                                                                                                                                                                                                                                                                           
     |                                                                                                                                                                                                                                                                                                                 
     |  discarded                                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  discards                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  jokers                                                                                                                                                                                                                                                                                                         
     |                                                                                                                                                                                                                                                                                                                 
     |  money                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  plays                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  required_score                                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  round                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  score                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  selected                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  stage                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                       
    class Stage(object) -> Not important
'''

import pylatro
import expectimax
import time

if __name__ == "__main__":
    print("Running Expectimax...")

    config = pylatro.Config()
    #config.ante_end = 1
    game = pylatro.GameEngine(config)

    start = time.perf_counter()
    score, win = expectimax.run_expectimax(game, depth=3)
    end = time.perf_counter()

    print("Expectimax finished")
    print(score, win)
    print(f"Time: {end - start:.2f} seconds")

