'''
Authors: Joshua Moellers
The code for Running the balatro simulations and also for testing the simulations
'''

'''
class Config(object)
     |  Static methods defined here:
     |
     |  __new__(*args, **kwargs)
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |                                                                                                                                                                                                                                                                                                                 
     |  ante_end                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  available_max                                                                                                                                                                                                                                                                                                  
     |                                                                                                                                                                                                                                                                                                                 
     |  deck_max                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  discarded_max                                                                                                                                                                                                                                                                                                  
     |                                                                                                                                                                                                                                                                                                                 
     |  discards                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  joker_slots                                                                                                                                                                                                                                                                                                    
     |                                                                                                                                                                                                                                                                                                                 
     |  joker_slots_max                                                                                                                                                                                                                                                                                                
     |                                                                                                                                                                                                                                                                                                                 
     |  money_max                                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  plays                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  selected_max                                                                                                                                                                                                                                                                                                   
     |                                                                                                                                                                                                                                                                                                                 
     |  stage_max                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                       
    class GameEngine(object)                                                                                                                                                                                                                                                                                           
     |  GameEngine(config=None)                                                                                                                                                                                                                                                                                        
     |                                                                                                                                                                                                                                                                                                                 
     |  Methods defined here:                                                                                                                                                                                                                                                                                          
     |
     |  copy() -> added by Joshua Moellers
     |                                                                                                                                                                                                                                                                                                                 
     |  gen_action_space(self, /)                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  gen_actions(self, /)                                                                                                                                                                                                                                                                                           
     |                                                                                                                                                                                                                                                                                                                 
     |  handle_action(self, /, action)                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  handle_action_index(self, /, index)                                                                                                                                                                                                                                                                            
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Static methods defined here:                                                                                                                                                                                                                                                                                   
     |                                                                                                                                                                                                                                                                                                                 
     |  __new__(*args, **kwargs)                                                                                                                                                                                                                                                                                       
     |      Create and return a new object.  See help(type) for accurate signature.                                                                                                                                                                                                                                    
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Data descriptors defined here:                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  is_over                                                                                                                                                                                                                                                                                                        
     |                                                                                                                                                                                                                                                                                                                 
     |  is_win                                                                                                                                                                                                                                                                                                         
     |                                                                                                                                                                                                                                                                                                                 
     |  state                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                       
    class GameState(object)                                                                                                                                                                                                                                                                                            
     |  Methods defined here:                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  __repr__(self, /)                                                                                                                                                                                                                                                                                              
     |      Return repr(self).                                                                                                                                                                                                                                                                                         
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Static methods defined here:                                                                                                                                                                                                                                                                                   
     |                                                                                                                                                                                                                                                                                                                 
     |  __new__(*args, **kwargs)                                                                                                                                                                                                                                                                                       
     |      Create and return a new object.  See help(type) for accurate signature.                                                                                                                                                                                                                                    
     |                                                                                                                                                                                                                                                                                                                 
     |  ----------------------------------------------------------------------                                                                                                                                                                                                                                         
     |  Data descriptors defined here:                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  action_history                                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  available                                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  deck                                                                                                                                                                                                                                                                                                           
     |                                                                                                                                                                                                                                                                                                                 
     |  discarded                                                                                                                                                                                                                                                                                                      
     |                                                                                                                                                                                                                                                                                                                 
     |  discards                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  jokers                                                                                                                                                                                                                                                                                                         
     |                                                                                                                                                                                                                                                                                                                 
     |  money                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  plays                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  required_score                                                                                                                                                                                                                                                                                                 
     |                                                                                                                                                                                                                                                                                                                 
     |  round                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  score                                                                                                                                                                                                                                                                                                          
     |                                                                                                                                                                                                                                                                                                                 
     |  selected                                                                                                                                                                                                                                                                                                       
     |                                                                                                                                                                                                                                                                                                                 
     |  stage                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                       
    class Stage(object) -> Not important
'''

import pylatro
import expectimax
import expectimax_parallel
import time

def run_expectimax_once(algo, config=None, depth=3, sample=5, timing=True, printing=None):
    game = pylatro.GameEngine(config)
    if printing: print("Running " + printing + "...")
    if timing: start = time.perf_counter()
    score, win, state = algo(game, depth, sample)
    if timing: end = time.perf_counter()
    if printing: 
        print(score, win, "\n", state)
        print(printing + " Finished")
        print(f"Time: {end - start:.2f} seconds")
        print()

    return score, win, state, start, end

def run_expectimax_until_win(algo, config=None, depth=3, sample=5, timing=True, printing=None):
    while True:
        game = pylatro.GameEngine(config)
        if printing: print("Running " + printing + "...")
        if timing: start = time.perf_counter()
        score, win, state = algo(game, depth, sample)
        if timing: end = time.perf_counter()
        if printing: 
            print(score, win, "\n", state)
            print(printing + " Finished")
            print(f"Time: {end - start:.2f} seconds")
            print()
        if win: break

    return score, win, state, start, end

if __name__ == "__main__":
    run_expectimax_once(expectimax_parallel.run_expectimax, config=None, depth=3, sample=-1, timing=True, printing="Parallel Expectimax")
